export const isProductionEnvironment = process.env.NODE_ENV === 'production';

export const isTestEnvironment = Boolean(
  process.env.PLAYWRIGHT_TEST_BASE_URL ||
    process.env.PLAYWRIGHT ||
    process.env.CI_PLAYWRIGHT,
);

export const EXPERTISE_TAGS = {
  technology: [
    'Web Development',
    'Mobile Development',
    'Machine Learning',
    'Data Science',
    'Cybersecurity',
    'DevOps',
    'Cloud Computing',
    'Blockchain',
    'Game Development',
    'AR/VR',
    'IoT',
    'Database Administration',
    'Network Engineering',
    'AI/ML Engineering',
    'Frontend Development',
    'Backend Development',
    'Full Stack Development',
    'Quality Assurance',
    'Technical Writing',
    'Embedded Systems',
    'Quantum Computing',
    'Robotics',
    'Computer Vision',
    'Natural Language Processing',
  ],
  business: [
    'Marketing',
    'Finance',
    'Entrepreneurship',
    'Project Management',
    'Human Resources',
    'Sales',
    'Product Management',
    'Business Strategy',
    'Supply Chain',
    'E-commerce',
    'Consulting',
    'Digital Marketing',
    'Social Media Management',
    'Brand Management',
    'Market Research',
    'Business Development',
    'Risk Management',
    'Corporate Finance',
    'Investment Banking',
    'Operations Management',
    'Customer Success',
    'Change Management',
  ],
  healthcare: [
    'Medicine',
    'Nursing',
    'Pharmacy',
    'Public Health',
    'Mental Health',
    'Nutrition',
    'Physical Therapy',
    'Biotechnology',
    'Healthcare Administration',
    'Medical Research',
    'Epidemiology',
    'Health Informatics',
    'Medical Imaging',
    'Clinical Trials',
    'Healthcare Policy',
    'Medical Device Development',
    'Telemedicine',
    'Health Economics',
    'Medical Education',
    'Healthcare Quality',
  ],
  science: [
    'Physics',
    'Chemistry',
    'Biology',
    'Astronomy',
    'Environmental Science',
    'Mathematics',
    'Statistics',
    'Research Methodology',
    'Neuroscience',
    'Genetics',
    'Bioinformatics',
    'Materials Science',
    'Geoscience',
    'Oceanography',
    'Climate Science',
    'Quantum Physics',
    'Particle Physics',
    'Computational Science',
    'Scientific Computing',
    'Laboratory Research',
  ],
  creative: [
    'Graphic Design',
    'Content Creation',
    'Video Production',
    'Photography',
    'Illustration',
    'Animation',
    'Creative Writing',
    'Music Production',
    'Filmmaking',
    'Digital Art',
    '3D Modeling',
    'Sound Design',
    'Game Design',
    'Motion Graphics',
    'Brand Design',
    'Art Direction',
    'Creative Direction',
    'Visual Effects',
    'Storytelling',
  ],
  education: [
    'Teaching',
    'Curriculum Development',
    'Educational Technology',
    'E-learning',
    'Language Teaching',
    'Academic Research',
    'Special Education',
    'Educational Psychology',
    'Instructional Design',
    'Educational Leadership',
    'Student Counseling',
    'Educational Assessment',
    'Learning Analytics',
    'Educational Policy',
    'Teacher Training',
    'Educational Consulting',
    'STEM Education',
    'Early Childhood Education',
    'Higher Education',
    'Educational Research',
  ],
  legal: [
    'Law',
    'Intellectual Property',
    'Contracts',
    'Corporate Law',
    'International Law',
    'Compliance',
    'Criminal Law',
    'Civil Rights',
    'Environmental Law',
    'Tax Law',
    'Employment Law',
    'Immigration Law',
    'Privacy Law',
    'Cybersecurity Law',
    'Patent Law',
    'Legal Research',
    'Legal Writing',
    'Mediation',
    'Arbitration',
    'Legal Technology',
  ],
  engineering: [
    'Software Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Chemical Engineering',
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Environmental Engineering',
    'Industrial Engineering',
    'Systems Engineering',
    'Quality Engineering',
    'Process Engineering',
    'Structural Engineering',
    'Automotive Engineering',
    'Energy Engineering',
  ],
  data_analytics: [
    'Data Analysis',
    'Data Visualization',
    'Predictive Analytics',
    'Statistical Analysis',
    'Data Engineering',
    'Data Governance',
    'Data Mining',
    'Big Data',
    'Data Architecture',
    'Data Quality',
    'Data Strategy',
    'Data Modeling',
    'Data Integration',
    'Data Security',
  ],
  communication_media: [
    'Journalism',
    'Public Relations',
    'Content Strategy',
    'Digital Media',
    'Broadcast Media',
    'Media Production',
    'Corporate Communications',
    'Technical Communication',
    'Media Relations',
    'Copywriting',
    'Editing',
    'Publishing',
    'Media Planning',
  ],
  other: [
    'Agriculture',
    'Architecture',
    'Construction',
    'Culinary Arts',
    'Fashion',
    'Languages',
    'Philosophy',
    'Psychology',
    'Social Work',
    'Sports & Fitness',
    'Translation',
    'Travel & Tourism',
    'Urban Planning',
    'Sustainability',
    'Renewable Energy',
    'Environmental Conservation',
    'Cultural Studies',
    'Anthropology',
    'Sociology',
    'Political Science',
  ]
};

// Flattened list for easier access
export const ALL_EXPERTISE_TAGS = Object.values(EXPERTISE_TAGS).flat();

// Function to extract expertise tags from user input
export function extractExpertiseTags(input: string): string[] {
  if (!input) return [];
  
  const lowercaseInput = input.toLowerCase();
  return ALL_EXPERTISE_TAGS.filter(tag => 
    lowercaseInput.includes(tag.toLowerCase())
  );
}
